# Generated by Django 3.2.7 on 2021-10-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0002_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='size_after',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='size_before',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
