# Generated by Django 3.2.7 on 2021-10-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0003_auto_20211008_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compressed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compressed_image', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('size_before', models.CharField(blank=True, max_length=200, null=True)),
                ('size_after', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='size_after',
            new_name='current_size',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='size_before',
        ),
    ]
