# Generated by Django 3.2.7 on 2021-10-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0004_auto_20211009_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='action',
            field=models.CharField(choices=[('compress', 'compress'), ('resize', 'resize')], default='compress', max_length=50),
        ),
        migrations.AddField(
            model_name='upload',
            name='compress_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='resize_measurements',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='size_after',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
