# Generated by Django 3.2.7 on 2021-10-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0005_auto_20211009_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='resize_measurements',
        ),
        migrations.AddField(
            model_name='upload',
            name='resize_measure_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='resize_measure_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
