# Generated by Django 3.2.7 on 2021-10-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0006_auto_20211009_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='compress_percentage',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='resize_measure_x',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='resize_measure_y',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
    ]
