# Generated by Django 3.2.7 on 2021-10-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0007_auto_20211009_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='orignal_size_x_y',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
