# Generated by Django 3.2.7 on 2021-10-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0009_delete_compressed'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='will_be_delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
