# Generated by Django 3.2.7 on 2021-10-15 04:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('compressor', '0010_upload_will_be_delete_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='session',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
            preserve_default=False,
        ),
    ]
