# Generated by Django 3.2.7 on 2021-11-13 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0011_upload_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='session',
        ),
    ]
